name: torr_finder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: "^4.0.0"
  fluttertoast: "^8.0.3"
  flutter_launcher_icons: "^0.9.2"
  font_awesome_flutter: "^9.2.0"
  url_launcher: "^6.0.20"

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/Giri.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf